In [17]:
from StringIO import StringIO
from pandas import DataFrame

data =StringIO("""col1,col2,col3,col4,col5,col6
3,3090,21,f,2,3
4,231,22,m,2,3
5,9427,13,f,2,2
6,9942,7,m,2,3
7,6802,33,f,3,2
8,8579,11,f,2,4
9,8598,11,f,2,4
10,16729,23,m,1,1
11,8472,11,f,3,4
12,10976,21,f,3,3
13,2870,21,f,2,3
14,12032,10,f,3,4
15,16999,13,m,2,2
16,570,7,f,2,3
17,8485,11,f,2,4
18,8728,11,f,3,4
19,20861,9,f,2,2
20,19771,34,f,2,2
21,17964,10,f,2,2""")

df = DataFrame.from_csv(data, sep=",", index_col=False)
df.drop_duplicates(subset='col2')
#df.to_csv("no_dups.txt", index =  false)

    col1   col2  col3 col4  col5  col6
0      3   3090    21    f     2     3
1      4    231    22    m     2     3
2      5   9427    13    f     2     2
3      6   9942     7    m     2     3
4      7   6802    33    f     3     2
5      8   8579    11    f     2     4
6      9   8598    11    f     2     4
7     10  16729    23    m     1     1
8     11   8472    11    f     3     4
9     12  10976    21    f     3     3
10    13   2870    21    f     2     3
11    14  12032    10    f     3     4
12    15  16999    13    m     2     2
13    16    570     7    f     2     3
14    17   8485    11    f     2     4
15    18   8728    11    f     3     4
16    19  20861     9    f     2     2
17    20  19771    34    f     2     2
18    21  17964    10    f     2     2